# Generated by Django 5.2.7 on 2025-10-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trainee_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='assign_courses',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='expertise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
