# Generated by Django 5.2.7 on 2025-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trainer_assign_courses_trainer_bio_trainer_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='batches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
