# Generated by Django 5.2.7 on 2025-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_trainer_batches_trainer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_images/'),
        ),
    ]
