# Generated by Django 5.2.7 on 2025-10-03 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_course_category_course_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trainee',
            name='certificate_status',
            field=models.CharField(default='Issued', max_length=20),
        ),
        migrations.AddField(
            model_name='trainee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trainee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_images/'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainee_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainees', to='myapp.trainer'),
        ),
    ]
