# Generated by Django 5.2.7 on 2025-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_trainee_batch_trainee_certificate_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('posted_by', models.CharField(default='Admin', max_length=100)),
                ('academy', models.CharField(default='Vetri Academy', max_length=100)),
                ('category', models.CharField(choices=[('course_updates', 'Course Updates'), ('events', 'Events'), ('deadline', 'Deadline'), ('new_features', 'New Features')], default='course_updates', max_length=20)),
            ],
        ),
    ]
