# Generated by Django 5.2.7 on 2025-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AddField(
            model_name='announcement',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All'), ('trainers', 'Trainers'), ('trainees', 'Trainees')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
