# Generated by Django 5.2.7 on 2025-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_announcement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
