# Generated by Django 5.2.7 on 2025-10-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_announcement_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='admin_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
