# Generated by Django 5.2.7 on 2025-10-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_trainer_admin_locked_alter_announcement_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('remarks', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='myapp.trainee')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='myapp.trainer')),
            ],
        ),
    ]
