# Generated by Django 5.2.7 on 2025-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_dailyassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='daily_task',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainee',
            name='total_task',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
