# Generated by Django 5.2.7 on 2025-10-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_trainee_daily_task_trainee_total_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='completed_task',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
