# Generated by Django 5.2.7 on 2025-10-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_trainee_completed_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='pending_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
