# Generated by Django 5.2.7 on 2025-10-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_trainee_pending_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='myapp.trainee')),
            ],
            options={
                'unique_together': {('trainee', 'date')},
            },
        ),
    ]
