# Generated by Django 5.2.7 on 2025-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_traineeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('informed', 'Informed'), ('not_informed', 'Not Informed')], max_length=15),
        ),
    ]
