# Generated by Django 5.2.7 on 2025-10-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_sessionrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='upload_status',
            field=models.CharField(
                choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')],
                default='pending',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='session_recordings/'),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='session_url',
            field=models.URLField(
                help_text='URL to the session recording (YouTube, Google Drive, etc.)',
                default=''
            ),
        ),
    ]
