# Generated by Django 5.2.7 on 2025-10-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20251004_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrecording',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='session_url',
            field=models.URLField(help_text='URL to the session recording (YouTube, Google Drive, etc.)'),
        ),
    ]
