# Generated by Django 5.2.7 on 2025-10-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_sessionrecording_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this session is visible to trainees'),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
