# Generated by Django 5.2.7 on 2025-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20251004_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
