# Generated by Django 5.2.7 on 2025-10-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_certificate_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Uploaded certificate file', null=True, upload_to='certificates/'),
        ),
    ]
